[tool.poetry]
name = "myfitnesspal"
version = "0.1.0"
description = ""
authors = ["Rahul Bansal <rahul286@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
rich = "^13.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
